INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["backbone_preprocessing"]

DATASET:
  NAME: "IMLE"

MODEL:
  BACKBONE:
    NAME: "fused_cnn_resnet50_clip_vit"
  HEAD:
    NAME: "binary_classifier"
    DROPOUT: 0.2